import type { AuState } from "@/types/database";

export interface SuburbConfig {
  name: string;
  slug: string;
  state: AuState;
  regionSlug: string;
  regionName: string;
  businesses: number;
}

// Top 97 high-density suburbs (8+ active businesses each), used as static params
// for /hairdresser/[suburb] and /barber/[suburb]. Pulled 2026-04-26.
export const TOP_SUBURBS: SuburbConfig[] = [
  { name: 'Perth', slug: 'perth', state: 'WA', regionSlug: 'perth-cbd', regionName: 'Perth CBD', businesses: 54 },
  { name: 'Adelaide', slug: 'adelaide', state: 'SA', regionSlug: 'adelaide-cbd', regionName: 'Adelaide CBD', businesses: 52 },
  { name: 'Penrith', slug: 'penrith', state: 'NSW', regionSlug: 'sydney-west', regionName: 'Sydney West', businesses: 47 },
  { name: 'Sydney', slug: 'sydney', state: 'NSW', regionSlug: 'sydney-cbd', regionName: 'Sydney CBD', businesses: 45 },
  { name: 'Wagga Wagga', slug: 'wagga-wagga', state: 'NSW', regionSlug: 'wagga-wagga', regionName: 'Wagga Wagga', businesses: 43 },
  { name: 'Wollongong', slug: 'wollongong', state: 'NSW', regionSlug: 'wollongong', regionName: 'Wollongong', businesses: 41 },
  { name: 'South Yarra', slug: 'south-yarra', state: 'VIC', regionSlug: 'melbourne-inner-south', regionName: 'Melbourne Inner South', businesses: 40 },
  { name: 'Southport', slug: 'southport', state: 'QLD', regionSlug: 'gold-coast', regionName: 'Gold Coast', businesses: 40 },
  { name: 'Bendigo', slug: 'bendigo', state: 'VIC', regionSlug: 'bendigo', regionName: 'Bendigo', businesses: 39 },
  { name: 'Dubbo', slug: 'dubbo', state: 'NSW', regionSlug: 'dubbo', regionName: 'Dubbo', businesses: 39 },
  { name: 'Shepparton', slug: 'shepparton', state: 'VIC', regionSlug: 'shepparton', regionName: 'Shepparton', businesses: 39 },
  { name: 'Coffs Harbour', slug: 'coffs-harbour', state: 'NSW', regionSlug: 'coffs-harbour', regionName: 'Coffs Harbour', businesses: 38 },
  { name: 'Maroochydore', slug: 'maroochydore', state: 'QLD', regionSlug: 'sunshine-coast', regionName: 'Sunshine Coast', businesses: 38 },
  { name: 'Craigieburn', slug: 'craigieburn', state: 'VIC', regionSlug: 'melbourne-north', regionName: 'Melbourne North', businesses: 37 },
  { name: 'Surry Hills', slug: 'surry-hills', state: 'NSW', regionSlug: 'sydney-cbd', regionName: 'Sydney CBD', businesses: 37 },
  { name: 'Port Macquarie', slug: 'port-macquarie', state: 'NSW', regionSlug: 'port-macquarie', regionName: 'Port Macquarie', businesses: 35 },
  { name: 'Hobart', slug: 'hobart', state: 'TAS', regionSlug: 'hobart', regionName: 'Hobart', businesses: 35 },
  { name: 'Liverpool', slug: 'liverpool', state: 'NSW', regionSlug: 'sydney-south-west', regionName: 'Sydney South West', businesses: 35 },
  { name: 'Newtown', slug: 'newtown', state: 'NSW', regionSlug: 'sydney-inner-west', regionName: 'Sydney Inner West', businesses: 35 },
  { name: 'Albury', slug: 'albury', state: 'NSW', regionSlug: 'wodonga', regionName: 'Wodonga', businesses: 34 },
  { name: 'Footscray', slug: 'footscray', state: 'VIC', regionSlug: 'melbourne-west', regionName: 'Melbourne West', businesses: 34 },
  { name: 'Bundaberg Central', slug: 'bundaberg-central', state: 'QLD', regionSlug: 'bundaberg', regionName: 'Bundaberg', businesses: 33 },
  { name: 'Ballarat Central', slug: 'ballarat-central', state: 'VIC', regionSlug: 'ballarat', regionName: 'Ballarat', businesses: 33 },
  { name: 'Prahran', slug: 'prahran', state: 'VIC', regionSlug: 'melbourne-inner-south', regionName: 'Melbourne Inner South', businesses: 33 },
  { name: 'Bondi Junction', slug: 'bondi-junction', state: 'NSW', regionSlug: 'sydney-eastern-suburbs', regionName: 'Sydney Eastern Suburbs', businesses: 33 },
  { name: 'Subiaco', slug: 'subiaco', state: 'WA', regionSlug: 'perth-cbd', regionName: 'Perth CBD', businesses: 33 },
  { name: 'Robina', slug: 'robina', state: 'QLD', regionSlug: 'gold-coast', regionName: 'Gold Coast', businesses: 33 },
  { name: 'Launceston', slug: 'launceston', state: 'TAS', regionSlug: 'launceston', regionName: 'Launceston', businesses: 32 },
  { name: 'Mount Gambier', slug: 'mount-gambier', state: 'SA', regionSlug: 'mount-gambier', regionName: 'Mount Gambier', businesses: 31 },
  { name: 'Toowoomba City', slug: 'toowoomba-city', state: 'QLD', regionSlug: 'toowoomba', regionName: 'Toowoomba', businesses: 31 },
  { name: 'Marrickville', slug: 'marrickville', state: 'NSW', regionSlug: 'sydney-inner-west', regionName: 'Sydney Inner West', businesses: 31 },
  { name: 'Dandenong', slug: 'dandenong', state: 'VIC', regionSlug: 'melbourne-south-east', regionName: 'Melbourne South East', businesses: 31 },
  { name: 'Darlinghurst', slug: 'darlinghurst', state: 'NSW', regionSlug: 'sydney-cbd', regionName: 'Sydney CBD', businesses: 31 },
  { name: 'Bankstown', slug: 'bankstown', state: 'NSW', regionSlug: 'sydney-south-west', regionName: 'Sydney South West', businesses: 31 },
  { name: 'Melbourne', slug: 'melbourne', state: 'VIC', regionSlug: 'melbourne-inner-south', regionName: 'Melbourne Inner South', businesses: 30 },
  { name: 'Parramatta', slug: 'parramatta', state: 'NSW', regionSlug: 'sydney-west', regionName: 'Sydney West', businesses: 30 },
  { name: 'Canberra', slug: 'canberra', state: 'ACT', regionSlug: 'canberra', regionName: 'Canberra', businesses: 30 },
  { name: 'Sunbury', slug: 'sunbury', state: 'VIC', regionSlug: 'sunbury', regionName: 'Sunbury', businesses: 29 },
  { name: 'Potts Point', slug: 'potts-point', state: 'NSW', regionSlug: 'sydney-cbd', regionName: 'Sydney CBD', businesses: 29 },
  { name: 'Caloundra', slug: 'caloundra', state: 'QLD', regionSlug: 'sunshine-coast', regionName: 'Sunshine Coast', businesses: 29 },
  { name: 'Nerang', slug: 'nerang', state: 'QLD', regionSlug: 'gold-coast', regionName: 'Gold Coast', businesses: 29 },
  { name: 'Brisbane City', slug: 'brisbane-city', state: 'QLD', regionSlug: 'brisbane-cbd', regionName: 'Brisbane CBD', businesses: 29 },
  { name: 'Orange', slug: 'orange', state: 'NSW', regionSlug: 'orange', regionName: 'Orange', businesses: 29 },
  { name: 'Tamworth', slug: 'tamworth', state: 'NSW', regionSlug: 'tamworth', regionName: 'Tamworth', businesses: 28 },
  { name: 'Albany', slug: 'albany', state: 'WA', regionSlug: 'albany', regionName: 'Albany', businesses: 28 },
  { name: 'Frankston', slug: 'frankston', state: 'VIC', regionSlug: 'melbourne-south-east', regionName: 'Melbourne South East', businesses: 28 },
  { name: 'Hornsby', slug: 'hornsby', state: 'NSW', regionSlug: 'sydney-north-shore', regionName: 'Sydney North Shore', businesses: 28 },
  { name: 'Cairns City', slug: 'cairns-city', state: 'QLD', regionSlug: 'cairns', regionName: 'Cairns', businesses: 28 },
  { name: 'Mornington', slug: 'mornington', state: 'VIC', regionSlug: 'mornington-peninsula', regionName: 'Mornington Peninsula', businesses: 28 },
  { name: 'Maroubra', slug: 'maroubra', state: 'NSW', regionSlug: 'sydney-eastern-suburbs', regionName: 'Sydney Eastern Suburbs', businesses: 28 },
  { name: 'Werribee', slug: 'werribee', state: 'VIC', regionSlug: 'melbourne-west', regionName: 'Melbourne West', businesses: 28 },
  { name: 'Castle Hill', slug: 'castle-hill', state: 'NSW', regionSlug: 'sydney-west', regionName: 'Sydney West', businesses: 27 },
  { name: 'Traralgon', slug: 'traralgon', state: 'VIC', regionSlug: 'traralgon', regionName: 'Traralgon', businesses: 27 },
  { name: 'Caringbah', slug: 'caringbah', state: 'NSW', regionSlug: 'sydney-south-west', regionName: 'Sydney South West', businesses: 27 },
  { name: 'Richmond', slug: 'richmond', state: 'VIC', regionSlug: 'melbourne-inner-south', regionName: 'Melbourne Inner South', businesses: 27 },
  { name: 'Fortitude Valley', slug: 'fortitude-valley', state: 'QLD', regionSlug: 'brisbane-cbd', regionName: 'Brisbane CBD', businesses: 27 },
  { name: 'Mackay', slug: 'mackay', state: 'QLD', regionSlug: 'mackay', regionName: 'Mackay', businesses: 27 },
  { name: 'Blacktown', slug: 'blacktown', state: 'NSW', regionSlug: 'sydney-west', regionName: 'Sydney West', businesses: 26 },
  { name: 'Warrnambool', slug: 'warrnambool', state: 'VIC', regionSlug: 'warrnambool', regionName: 'Warrnambool', businesses: 26 },
  { name: 'Cheltenham', slug: 'cheltenham', state: 'VIC', regionSlug: 'melbourne-south-east', regionName: 'Melbourne South East', businesses: 26 },
  { name: 'Merrylands', slug: 'merrylands', state: 'NSW', regionSlug: 'sydney-west', regionName: 'Sydney West', businesses: 26 },
  { name: 'Norwood', slug: 'norwood', state: 'SA', regionSlug: 'adelaide-east', regionName: 'Adelaide East', businesses: 26 },
  { name: 'Surfers Paradise', slug: 'surfers-paradise', state: 'QLD', regionSlug: 'gold-coast', regionName: 'Gold Coast', businesses: 26 },
  { name: 'Sunshine', slug: 'sunshine', state: 'VIC', regionSlug: 'melbourne-west', regionName: 'Melbourne West', businesses: 26 },
  { name: 'Chatswood', slug: 'chatswood', state: 'NSW', regionSlug: 'sydney-north-shore', regionName: 'Sydney North Shore', businesses: 26 },
  { name: 'Mildura', slug: 'mildura', state: 'VIC', regionSlug: 'mildura', regionName: 'Mildura', businesses: 26 },
  { name: 'Joondalup', slug: 'joondalup', state: 'WA', regionSlug: 'perth-north', regionName: 'Perth North', businesses: 26 },
  { name: 'St Kilda', slug: 'st-kilda', state: 'VIC', regionSlug: 'melbourne-inner-south', regionName: 'Melbourne Inner South', businesses: 25 },
  { name: 'Darwin City', slug: 'darwin-city', state: 'NT', regionSlug: 'darwin', regionName: 'Darwin', businesses: 25 },
  { name: 'Preston', slug: 'preston', state: 'VIC', regionSlug: 'melbourne-north', regionName: 'Melbourne North', businesses: 25 },
  { name: 'Greensborough', slug: 'greensborough', state: 'VIC', regionSlug: 'melbourne-north', regionName: 'Melbourne North', businesses: 25 },
  { name: 'Bunbury', slug: 'bunbury', state: 'WA', regionSlug: 'bunbury', regionName: 'Bunbury', businesses: 25 },
  { name: 'Berwick', slug: 'berwick', state: 'VIC', regionSlug: 'melbourne-south-east', regionName: 'Melbourne South East', businesses: 25 },
  { name: 'Camberwell', slug: 'camberwell', state: 'VIC', regionSlug: 'melbourne-east', regionName: 'Melbourne East', businesses: 25 },
  { name: 'Mandurah', slug: 'mandurah', state: 'WA', regionSlug: 'perth-south', regionName: 'Perth South', businesses: 25 },
  { name: 'Haymarket', slug: 'haymarket', state: 'NSW', regionSlug: 'sydney-cbd', regionName: 'Sydney CBD', businesses: 25 },
  { name: 'Burleigh Heads', slug: 'burleigh-heads', state: 'QLD', regionSlug: 'gold-coast', regionName: 'Gold Coast', businesses: 25 },
  { name: 'Manly', slug: 'manly', state: 'NSW', regionSlug: 'sydney-northern-beaches', regionName: 'Sydney Northern Beaches', businesses: 25 },
  { name: 'Buderim', slug: 'buderim', state: 'QLD', regionSlug: 'sunshine-coast', regionName: 'Sunshine Coast', businesses: 24 },
  { name: 'Echuca', slug: 'echuca', state: 'VIC', regionSlug: 'echuca', regionName: 'Echuca', businesses: 24 },
  { name: 'Randwick', slug: 'randwick', state: 'NSW', regionSlug: 'sydney-eastern-suburbs', regionName: 'Sydney Eastern Suburbs', businesses: 24 },
  { name: 'Rockdale', slug: 'rockdale', state: 'NSW', regionSlug: 'sydney-south-west', regionName: 'Sydney South West', businesses: 24 },
  { name: 'Wynnum', slug: 'wynnum', state: 'QLD', regionSlug: 'brisbane-inner-south', regionName: 'Brisbane Inner South', businesses: 24 },
  { name: 'Lismore', slug: 'lismore', state: 'NSW', regionSlug: 'lismore', regionName: 'Lismore', businesses: 24 },
  { name: 'Bathurst', slug: 'bathurst', state: 'NSW', regionSlug: 'bathurst', regionName: 'Bathurst', businesses: 24 },
  { name: 'West End', slug: 'west-end', state: 'QLD', regionSlug: 'brisbane-cbd', regionName: 'Brisbane CBD', businesses: 24 },
  { name: 'Brunswick', slug: 'brunswick', state: 'VIC', regionSlug: 'melbourne-inner-north', regionName: 'Melbourne Inner North', businesses: 24 },
  { name: 'Leichhardt', slug: 'leichhardt', state: 'NSW', regionSlug: 'sydney-inner-west', regionName: 'Sydney Inner West', businesses: 24 },
  { name: 'Campsie', slug: 'campsie', state: 'NSW', regionSlug: 'sydney-south-west', regionName: 'Sydney South West', businesses: 23 },
  { name: 'Wangaratta', slug: 'wangaratta', state: 'VIC', regionSlug: 'wangaratta', regionName: 'Wangaratta', businesses: 23 },
  { name: 'Cronulla', slug: 'cronulla', state: 'NSW', regionSlug: 'sydney-south-west', regionName: 'Sydney South West', businesses: 23 },
  { name: 'Pakenham', slug: 'pakenham', state: 'VIC', regionSlug: 'melbourne-south-east', regionName: 'Melbourne South East', businesses: 23 },
  { name: 'Devonport', slug: 'devonport', state: 'TAS', regionSlug: 'devonport', regionName: 'Devonport', businesses: 23 },
  { name: 'Geelong', slug: 'geelong', state: 'VIC', regionSlug: 'geelong', regionName: 'Geelong', businesses: 23 },
  { name: 'North Perth', slug: 'north-perth', state: 'WA', regionSlug: 'perth-cbd', regionName: 'Perth CBD', businesses: 23 },
  { name: 'Springvale', slug: 'springvale', state: 'VIC', regionSlug: 'melbourne-south-east', regionName: 'Melbourne South East', businesses: 23 },
  { name: 'Northcote', slug: 'northcote', state: 'VIC', regionSlug: 'melbourne-inner-north', regionName: 'Melbourne Inner North', businesses: 22 },
];
