import type { AuState } from "@/types/database";

export interface SuburbConfig {
  name: string;
  slug: string;
  state: AuState;
  regionSlug: string;
  regionName: string;
  businesses: number;
}

// Top 97 high-density suburbs (8+ active businesses each), used as static params
// for /hairdresser/[suburb] and /barber/[suburb]. Pulled 2026-04-26.
export const TOP_SUBURBS: SuburbConfig[] = [
  { name: 'Perth', slug: 'perth', state: 'WA', regionSlug: 'perth-cbd', regionName: 'Perth CBD', businesses: 54 },
  { name: 'Adelaide', slug: 'adelaide', state: 'SA', regionSlug: 'adelaide-cbd', regionName: 'Adelaide CBD', businesses: 52 },
  { name: 'Penrith', slug: 'penrith', state: 'NSW', regionSlug: 'sydney-west', regionName: 'Sydney West', businesses: 47 },
  { name: 'Sydney', slug: 'sydney', state: 'NSW', regionSlug: 'sydney-cbd', regionName: 'Sydney CBD', businesses: 45 },
  { name: 'Wagga Wagga', slug: 'wagga-wagga', state: 'NSW', regionSlug: 'wagga-wagga', regionName: 'Wagga Wagga', businesses: 43 },
  { name: 'Wollongong', slug: 'wollongong', state: 'NSW', regionSlug: 'wollongong', regionName: 'Wollongong', businesses: 41 },
  { name: 'South Yarra', slug: 'south-yarra', state: 'VIC', regionSlug: 'melbourne-inner-south', regionName: 'Melbourne Inner South', businesses: 40 },
  { name: 'Southport', slug: 'southport', state: 'QLD', regionSlug: 'gold-coast', regionName: 'Gold Coast', businesses: 40 },
  { name: 'Bendigo', slug: 'bendigo', state: 'VIC', regionSlug: 'bendigo', regionName: 'Bendigo', businesses: 39 },
  { name: 'Dubbo', slug: 'dubbo', state: 'NSW', regionSlug: 'dubbo', regionName: 'Dubbo', businesses: 39 },
  { name: 'Shepparton', slug: 'shepparton', state: 'VIC', regionSlug: 'shepparton', regionName: 'Shepparton', businesses: 39 },
  { name: 'Coffs Harbour', slug: 'coffs-harbour', state: 'NSW', regionSlug: 'coffs-harbour', regionName: 'Coffs Harbour', businesses: 38 },
  { name: 'Maroochydore', slug: 'maroochydore', state: 'QLD', regionSlug: 'sunshine-coast', regionName: 'Sunshine Coast', businesses: 38 },
  { name: 'Craigieburn', slug: 'craigieburn', state: 'VIC', regionSlug: 'melbourne-north', regionName: 'Melbourne North', businesses: 37 },
  { name: 'Surry Hills', slug: 'surry-hills', state: 'NSW', regionSlug: 'sydney-cbd', regionName: 'Sydney CBD', businesses: 37 },
  { name: 'Port Macquarie', slug: 'port-macquarie', state: 'NSW', regionSlug: 'port-macquarie', regionName: 'Port Macquarie', businesses: 35 },
  { name: 'Hobart', slug: 'hobart', state: 'TAS', regionSlug: 'hobart', regionName: 'Hobart', businesses: 35 },
  { name: 'Liverpool', slug: 'liverpool', state: 'NSW', regionSlug: 'sydney-south-west', regionName: 'Sydney South West', businesses: 35 },
  { name: 'Newtown', slug: 'newtown', state: 'NSW', regionSlug: 'sydney-inner-west', regionName: 'Sydney Inner West', businesses: 35 },
  { name: 'Albury', slug: 'albury', state: 'NSW', regionSlug: 'wodonga', regionName: 'Wodonga', businesses: 34 },
  { name: 'Footscray', slug: 'footscray', state: 'VIC', regionSlug: 'melbourne-west', regionName: 'Melbourne West', businesses: 34 },
  { name: 'Bundaberg Central', slug: 'bundaberg-central', state: 'QLD', regionSlug: 'bundaberg', regionName: 'Bundaberg', businesses: 33 },
  { name: 'Ballarat Central', slug: 'ballarat-central', state: 'VIC', regionSlug: 'ballarat', regionName: 'Ballarat', businesses: 33 },
  { name: 'Prahran', slug: 'prahran', state: 'VIC', regionSlug: 'melbourne-inner-south', regionName: 'Melbourne Inner South', businesses: 33 },
  { name: 'Bondi Junction', slug: 'bondi-junction', state: 'NSW', regionSlug: 'sydney-eastern-suburbs', regionName: 'Sydney Eastern Suburbs', businesses: 33 },
  { name: 'Subiaco', slug: 'subiaco', state: 'WA', regionSlug: 'perth-cbd', regionName: 'Perth CBD', businesses: 33 },
  { name: 'Robina', slug: 'robina', state: 'QLD', regionSlug: 'gold-coast', regionName: 'Gold Coast', businesses: 33 },
  { name: 'Launceston', slug: 'launceston', state: 'TAS', regionSlug: 'launceston', regionName: 'Launceston', businesses: 32 },
  { name: 'Mount Gambier', slug: 'mount-gambier', state: 'SA', regionSlug: 'mount-gambier', regionName: 'Mount Gambier', businesses: 31 },
  { name: 'Toowoomba City', slug: 'toowoomba-city', state: 'QLD', regionSlug: 'toowoomba', regionName: 'Toowoomba', businesses: 31 },
  { name: 'Marrickville', slug: 'marrickville', state: 'NSW', regionSlug: 'sydney-inner-west', regionName: 'Sydney Inner West', businesses: 31 },
  { name: 'Dandenong', slug: 'dandenong', state: 'VIC', regionSlug: 'melbourne-south-east', regionName: 'Melbourne South East', businesses: 31 },
  { name: 'Darlinghurst', slug: 'darlinghurst', state: 'NSW', regionSlug: 'sydney-cbd', regionName: 'Sydney CBD', businesses: 31 },
  { name: 'Bankstown', slug: 'bankstown', state: 'NSW', regionSlug: 'sydney-south-west', regionName: 'Sydney South West', businesses: 31 },
  { name: 'Melbourne', slug: 'melbourne', state: 'VIC', regionSlug: 'melbourne-inner-south', regionName: 'Melbourne Inner South', businesses: 30 },
  { name: 'Parramatta', slug: 'parramatta', state: 'NSW', regionSlug: 'sydney-west', regionName: 'Sydney West', businesses: 30 },
  { name: 'Canberra', slug: 'canberra', state: 'ACT', regionSlug: 'canberra', regionName: 'Canberra', businesses: 30 },
  { name: 'Sunbury', slug: 'sunbury', state: 'VIC', regionSlug: 'sunbury', regionName: 'Sunbury', businesses: 29 },
  { name: 'Potts Point', slug: 'potts-point', state: 'NSW', regionSlug: 'sydney-cbd', regionName: 'Sydney CBD', businesses: 29 },
  { name: 'Caloundra', slug: 'caloundra', state: 'QLD', regionSlug: 'sunshine-coast', regionName: 'Sunshine Coast', businesses: 29 },
  { name: 'Nerang', slug: 'nerang', state: 'QLD', regionSlug: 'gold-coast', regionName: 'Gold Coast', businesses: 29 },
  { name: 'Brisbane City', slug: 'brisbane-city', state: 'QLD', regionSlug: 'brisbane-cbd', regionName: 'Brisbane CBD', businesses: 29 },
  { name: 'Orange', slug: 'orange', state: 'NSW', regionSlug: 'orange', regionName: 'Orange', businesses: 29 },
  { name: 'Tamworth', slug: 'tamworth', state: 'NSW', regionSlug: 'tamworth', regionName: 'Tamworth', businesses: 28 },
  { name: 'Albany', slug: 'albany', state: 'WA', regionSlug: 'albany', regionName: 'Albany', businesses: 28 },
  { name: 'Frankston', slug: 'frankston', state: 'VIC', regionSlug: 'melbourne-south-east', regionName: 'Melbourne South East', businesses: 28 },
  { name: 'Hornsby', slug: 'hornsby', state: 'NSW', regionSlug: 'sydney-north-shore', regionName: 'Sydney North Shore', businesses: 28 },
  { name: 'Cairns City', slug: 'cairns-city', state: 'QLD', regionSlug: 'cairns', regionName: 'Cairns', businesses: 28 },
  { name: 'Mornington', slug: 'mornington', state: 'VIC', regionSlug: 'mornington-peninsula', regionName: 'Mornington Peninsula', businesses: 28 },
  { name: 'Maroubra', slug: 'maroubra', state: 'NSW', regionSlug: 'sydney-eastern-suburbs', regionName: 'Sydney Eastern Suburbs', businesses: 28 },
  { name: 'Werribee', slug: 'werribee', state: 'VIC', regionSlug: 'melbourne-west', regionName: 'Melbourne West', businesses: 28 },
  { name: 'Castle Hill', slug: 'castle-hill', state: 'NSW', regionSlug: 'sydney-west', regionName: 'Sydney West', businesses: 27 },
  { name: 'Traralgon', slug: 'traralgon', state: 'VIC', regionSlug: 'traralgon', regionName: 'Traralgon', businesses: 27 },
  { name: 'Caringbah', slug: 'caringbah', state: 'NSW', regionSlug: 'sydney-south-west', regionName: 'Sydney South West', businesses: 27 },
  { name: 'Richmond', slug: 'richmond', state: 'VIC', regionSlug: 'melbourne-inner-south', regionName: 'Melbourne Inner South', businesses: 27 },
  { name: 'Fortitude Valley', slug: 'fortitude-valley', state: 'QLD', regionSlug: 'brisbane-cbd', regionName: 'Brisbane CBD', businesses: 27 },
  { name: 'Mackay', slug: 'mackay', state: 'QLD', regionSlug: 'mackay', regionName: 'Mackay', businesses: 27 },
  { name: 'Blacktown', slug: 'blacktown', state: 'NSW', regionSlug: 'sydney-west', regionName: 'Sydney West', businesses: 26 },
  { name: 'Warrnambool', slug: 'warrnambool', state: 'VIC', regionSlug: 'warrnambool', regionName: 'Warrnambool', businesses: 26 },
  { name: 'Cheltenham', slug: 'cheltenham', state: 'VIC', regionSlug: 'melbourne-south-east', regionName: 'Melbourne South East', businesses: 26 },
  { name: 'Merrylands', slug: 'merrylands', state: 'NSW', regionSlug: 'sydney-west', regionName: 'Sydney West', businesses: 26 },
  { name: 'Norwood', slug: 'norwood', state: 'SA', regionSlug: 'adelaide-east', regionName: 'Adelaide East', businesses: 26 },
  { name: 'Surfers Paradise', slug: 'surfers-paradise', state: 'QLD', regionSlug: 'gold-coast', regionName: 'Gold Coast', businesses: 26 },
  { name: 'Sunshine', slug: 'sunshine', state: 'VIC', regionSlug: 'melbourne-west', regionName: 'Melbourne West', businesses: 26 },
  { name: 'Chatswood', slug: 'chatswood', state: 'NSW', regionSlug: 'sydney-north-shore', regionName: 'Sydney North Shore', businesses: 26 },
  { name: 'Mildura', slug: 'mildura', state: 'VIC', regionSlug: 'mildura', regionName: 'Mildura', businesses: 26 },
  { name: 'Joondalup', slug: 'joondalup', state: 'WA', regionSlug: 'perth-north', regionName: 'Perth North', businesses: 26 },
  { name: 'St Kilda', slug: 'st-kilda', state: 'VIC', regionSlug: 'melbourne-inner-south', regionName: 'Melbourne Inner South', businesses: 25 },
  { name: 'Darwin City', slug: 'darwin-city', state: 'NT', regionSlug: 'darwin', regionName: 'Darwin', businesses: 25 },
  { name: 'Preston', slug: 'preston', state: 'VIC', regionSlug: 'melbourne-north', regionName: 'Melbourne North', businesses: 25 },
  { name: 'Greensborough', slug: 'greensborough', state: 'VIC', regionSlug: 'melbourne-north', regionName: 'Melbourne North', businesses: 25 },
  { name: 'Bunbury', slug: 'bunbury', state: 'WA', regionSlug: 'bunbury', regionName: 'Bunbury', businesses: 25 },
  { name: 'Berwick', slug: 'berwick', state: 'VIC', regionSlug: 'melbourne-south-east', regionName: 'Melbourne South East', businesses: 25 },
  { name: 'Camberwell', slug: 'camberwell', state: 'VIC', regionSlug: 'melbourne-east', regionName: 'Melbourne East', businesses: 25 },
  { name: 'Mandurah', slug: 'mandurah', state: 'WA', regionSlug: 'perth-south', regionName: 'Perth South', businesses: 25 },
  { name: 'Haymarket', slug: 'haymarket', state: 'NSW', regionSlug: 'sydney-cbd', regionName: 'Sydney CBD', businesses: 25 },
  { name: 'Burleigh Heads', slug: 'burleigh-heads', state: 'QLD', regionSlug: 'gold-coast', regionName: 'Gold Coast', businesses: 25 },
  { name: 'Manly', slug: 'manly', state: 'NSW', regionSlug: 'sydney-northern-beaches', regionName: 'Sydney Northern Beaches', businesses: 25 },
  { name: 'Buderim', slug: 'buderim', state: 'QLD', regionSlug: 'sunshine-coast', regionName: 'Sunshine Coast', businesses: 24 },
  { name: 'Echuca', slug: 'echuca', state: 'VIC', regionSlug: 'echuca', regionName: 'Echuca', businesses: 24 },
  { name: 'Randwick', slug: 'randwick', state: 'NSW', regionSlug: 'sydney-eastern-suburbs', regionName: 'Sydney Eastern Suburbs', businesses: 24 },
  { name: 'Rockdale', slug: 'rockdale', state: 'NSW', regionSlug: 'sydney-south-west', regionName: 'Sydney South West', businesses: 24 },
  { name: 'Wynnum', slug: 'wynnum', state: 'QLD', regionSlug: 'brisbane-inner-south', regionName: 'Brisbane Inner South', businesses: 24 },
  { name: 'Lismore', slug: 'lismore', state: 'NSW', regionSlug: 'lismore', regionName: 'Lismore', businesses: 24 },
  { name: 'Bathurst', slug: 'bathurst', state: 'NSW', regionSlug: 'bathurst', regionName: 'Bathurst', businesses: 24 },
  { name: 'West End', slug: 'west-end', state: 'QLD', regionSlug: 'brisbane-cbd', regionName: 'Brisbane CBD', businesses: 24 },
  { name: 'Brunswick', slug: 'brunswick', state: 'VIC', regionSlug: 'melbourne-inner-north', regionName: 'Melbourne Inner North', businesses: 24 },
  { name: 'Leichhardt', slug: 'leichhardt', state: 'NSW', regionSlug: 'sydney-inner-west', regionName: 'Sydney Inner West', businesses: 24 },
  { name: 'Campsie', slug: 'campsie', state: 'NSW', regionSlug: 'sydney-south-west', regionName: 'Sydney South West', businesses: 23 },
  { name: 'Wangaratta', slug: 'wangaratta', state: 'VIC', regionSlug: 'wangaratta', regionName: 'Wangaratta', businesses: 23 },
  { name: 'Cronulla', slug: 'cronulla', state: 'NSW', regionSlug: 'sydney-south-west', regionName: 'Sydney South West', businesses: 23 },
  { name: 'Pakenham', slug: 'pakenham', state: 'VIC', regionSlug: 'melbourne-south-east', regionName: 'Melbourne South East', businesses: 23 },
  { name: 'Devonport', slug: 'devonport', state: 'TAS', regionSlug: 'devonport', regionName: 'Devonport', businesses: 23 },
  { name: 'Geelong', slug: 'geelong', state: 'VIC', regionSlug: 'geelong', regionName: 'Geelong', businesses: 23 },
  { name: 'North Perth', slug: 'north-perth', state: 'WA', regionSlug: 'perth-cbd', regionName: 'Perth CBD', businesses: 23 },
  { name: 'Springvale', slug: 'springvale', state: 'VIC', regionSlug: 'melbourne-south-east', regionName: 'Melbourne South East', businesses: 23 },
  { name: 'Northcote', slug: 'northcote', state: 'VIC', regionSlug: 'melbourne-inner-north', regionName: 'Melbourne Inner North', businesses: 22 },
  { name: 'Rockhampton', slug: 'rockhampton', state: 'QLD', regionSlug: 'rockhampton', regionName: 'Rockhampton', businesses: 18 },
  // Tier-2 expansion 2026-04-26 (14+ active businesses, NOT in tier-1)
  { name: 'Armidale', slug: 'armidale', state: 'NSW', regionSlug: 'sydney-cbd', regionName: 'Sydney CBD', businesses: 24 },
  { name: 'Paddington', slug: 'paddington', state: 'NSW', regionSlug: 'sydney-eastern-suburbs', regionName: 'Sydney Eastern Suburbs', businesses: 22 },
  { name: 'Midland', slug: 'midland', state: 'WA', regionSlug: 'perth-north', regionName: 'Perth North', businesses: 22 },
  { name: 'Mooloolaba', slug: 'mooloolaba', state: 'QLD', regionSlug: 'sunshine-coast', regionName: 'Sunshine Coast', businesses: 22 },
  { name: 'Kingsgrove', slug: 'kingsgrove', state: 'NSW', regionSlug: 'sydney-south-west', regionName: 'Sydney South West', businesses: 22 },
  { name: 'Point Cook', slug: 'point-cook', state: 'VIC', regionSlug: 'melbourne-west', regionName: 'Melbourne West', businesses: 22 },
  { name: 'Punchbowl', slug: 'punchbowl', state: 'NSW', regionSlug: 'sydney-south-west', regionName: 'Sydney South West', businesses: 22 },
  { name: 'Five Dock', slug: 'five-dock', state: 'NSW', regionSlug: 'sydney-inner-west', regionName: 'Sydney Inner West', businesses: 22 },
  { name: 'Saint Marys', slug: 'saint-marys', state: 'NSW', regionSlug: 'sydney-west', regionName: 'Sydney West', businesses: 22 },
  { name: 'Erina', slug: 'erina', state: 'NSW', regionSlug: 'central-coast', regionName: 'Central Coast', businesses: 22 },
  { name: 'Campbelltown', slug: 'campbelltown', state: 'NSW', regionSlug: 'adelaide-east', regionName: 'Adelaide East', businesses: 22 },
  { name: 'Fairfield', slug: 'fairfield', state: 'NSW', regionSlug: 'sydney-west', regionName: 'Sydney West', businesses: 22 },
  { name: 'Reservoir', slug: 'reservoir', state: 'VIC', regionSlug: 'melbourne-north', regionName: 'Melbourne North', businesses: 22 },
  { name: 'Dee Why', slug: 'dee-why', state: 'NSW', regionSlug: 'sydney-northern-beaches', regionName: 'Sydney Northern Beaches', businesses: 22 },
  { name: 'Ashfield', slug: 'ashfield', state: 'NSW', regionSlug: 'sydney-inner-west', regionName: 'Sydney Inner West', businesses: 22 },
  { name: 'Brunswick East', slug: 'brunswick-east', state: 'VIC', regionSlug: 'melbourne-inner-north', regionName: 'Melbourne Inner North', businesses: 22 },
  { name: 'Kogarah', slug: 'kogarah', state: 'NSW', regionSlug: 'sydney-south-west', regionName: 'Sydney South West', businesses: 22 },
  { name: 'Geraldton', slug: 'geraldton', state: 'WA', regionSlug: 'geraldton', regionName: 'Geraldton', businesses: 21 },
  { name: 'Double Bay', slug: 'double-bay', state: 'NSW', regionSlug: 'sydney-eastern-suburbs', regionName: 'Sydney Eastern Suburbs', businesses: 21 },
  { name: 'Brookvale', slug: 'brookvale', state: 'NSW', regionSlug: 'sydney-northern-beaches', regionName: 'Sydney Northern Beaches', businesses: 21 },
  { name: 'Malvern', slug: 'malvern', state: 'VIC', regionSlug: 'melbourne-east', regionName: 'Melbourne East', businesses: 21 },
  { name: 'Armadale', slug: 'armadale', state: 'WA', regionSlug: 'perth-south', regionName: 'Perth South', businesses: 21 },
  { name: 'Auburn', slug: 'auburn', state: 'NSW', regionSlug: 'sydney-west', regionName: 'Sydney West', businesses: 21 },
  { name: 'Helensvale', slug: 'helensvale', state: 'QLD', regionSlug: 'gold-coast', regionName: 'Gold Coast', businesses: 21 },
  { name: 'Balmain', slug: 'balmain', state: 'NSW', regionSlug: 'sydney-inner-west', regionName: 'Sydney Inner West', businesses: 20 },
  { name: 'Caroline Springs', slug: 'caroline-springs', state: 'VIC', regionSlug: 'caroline-springs', regionName: 'Caroline Springs', businesses: 20 },
  { name: 'Sandy Bay', slug: 'sandy-bay', state: 'TAS', regionSlug: 'hobart', regionName: 'Hobart', businesses: 20 },
  { name: 'Mosman', slug: 'mosman', state: 'NSW', regionSlug: 'sydney-north-shore', regionName: 'Sydney North Shore', businesses: 20 },
  { name: 'Mawson Lakes', slug: 'mawson-lakes', state: 'SA', regionSlug: 'adelaide-north', regionName: 'Adelaide North', businesses: 20 },
  { name: 'Morphett Vale', slug: 'morphett-vale', state: 'SA', regionSlug: 'adelaide-south', regionName: 'Adelaide South', businesses: 20 },
  { name: 'Phillip', slug: 'phillip', state: 'ACT', regionSlug: 'canberra', regionName: 'Canberra', businesses: 20 },
  { name: 'Rose Bay', slug: 'rose-bay', state: 'NSW', regionSlug: 'sydney-eastern-suburbs', regionName: 'Sydney Eastern Suburbs', businesses: 20 },
  { name: 'Neutral Bay', slug: 'neutral-bay', state: 'NSW', regionSlug: 'sydney-north-shore', regionName: 'Sydney North Shore', businesses: 20 },
  { name: 'Ballina', slug: 'ballina', state: 'NSW', regionSlug: 'ballina', regionName: 'Ballina', businesses: 20 },
  { name: 'Lane Cove', slug: 'lane-cove', state: 'NSW', regionSlug: 'sydney-north-shore', regionName: 'Sydney North Shore', businesses: 20 },
  { name: 'Cabramatta', slug: 'cabramatta', state: 'NSW', regionSlug: 'sydney-west', regionName: 'Sydney West', businesses: 20 },
  { name: 'Fremantle', slug: 'fremantle', state: 'WA', regionSlug: 'perth-south', regionName: 'Perth South', businesses: 20 },
  { name: 'Wodonga', slug: 'wodonga', state: 'VIC', regionSlug: 'wodonga', regionName: 'Wodonga', businesses: 20 },
  { name: 'Croydon', slug: 'croydon', state: 'VIC', regionSlug: 'melbourne-east', regionName: 'Melbourne East', businesses: 20 },
  { name: 'Broadbeach', slug: 'broadbeach', state: 'QLD', regionSlug: 'gold-coast', regionName: 'Gold Coast', businesses: 19 },
  { name: 'Burwood', slug: 'burwood', state: 'NSW', regionSlug: 'sydney-inner-west', regionName: 'Sydney Inner West', businesses: 19 },
  { name: 'Yeppoon', slug: 'yeppoon', state: 'QLD', regionSlug: 'rockhampton', regionName: 'Rockhampton', businesses: 19 },
  { name: 'Mount Waverley', slug: 'mount-waverley', state: 'VIC', regionSlug: 'melbourne-south-east', regionName: 'Melbourne South East', businesses: 19 },
  { name: 'Cleveland', slug: 'cleveland', state: 'QLD', regionSlug: 'brisbane-east', regionName: 'Brisbane East', businesses: 19 },
  { name: 'Horsham', slug: 'horsham', state: 'VIC', regionSlug: 'horsham', regionName: 'Horsham', businesses: 19 },
  { name: 'Labrador', slug: 'labrador', state: 'QLD', regionSlug: 'gold-coast', regionName: 'Gold Coast', businesses: 19 },
  { name: 'Morley', slug: 'morley', state: 'WA', regionSlug: 'perth-north', regionName: 'Perth North', businesses: 19 },
  { name: 'Rouse Hill', slug: 'rouse-hill', state: 'NSW', regionSlug: 'sydney-west', regionName: 'Sydney West', businesses: 19 },
  { name: 'Coolangatta', slug: 'coolangatta', state: 'QLD', regionSlug: 'tweed-heads', regionName: 'Tweed Heads', businesses: 19 },
  { name: 'Ellenbrook', slug: 'ellenbrook', state: 'WA', regionSlug: 'perth-north', regionName: 'Perth North', businesses: 19 },
  { name: 'Hawthorn', slug: 'hawthorn', state: 'VIC', regionSlug: 'melbourne-east', regionName: 'Melbourne East', businesses: 19 },
  { name: 'Mount Lawley', slug: 'mount-lawley', state: 'WA', regionSlug: 'perth-cbd', regionName: 'Perth CBD', businesses: 19 },
  { name: 'Swan Hill', slug: 'swan-hill', state: 'VIC', regionSlug: 'swan-hill', regionName: 'Swan Hill', businesses: 19 },
  { name: 'Newcastle', slug: 'newcastle', state: 'NSW', regionSlug: 'newcastle', regionName: 'Newcastle', businesses: 19 },
  { name: 'Christies Beach', slug: 'christies-beach', state: 'SA', regionSlug: 'adelaide-south', regionName: 'Adelaide South', businesses: 19 },
  { name: 'Mermaid Beach', slug: 'mermaid-beach', state: 'QLD', regionSlug: 'gold-coast', regionName: 'Gold Coast', businesses: 19 },
  { name: 'Hurstville', slug: 'hurstville', state: 'NSW', regionSlug: 'sydney-south-west', regionName: 'Sydney South West', businesses: 18 },
  { name: 'Williamstown', slug: 'williamstown', state: 'VIC', regionSlug: 'melbourne-west', regionName: 'Melbourne West', businesses: 18 },
  { name: 'Bundoora', slug: 'bundoora', state: 'VIC', regionSlug: 'melbourne-north', regionName: 'Melbourne North', businesses: 18 },
  { name: 'Byron Bay', slug: 'byron-bay', state: 'NSW', regionSlug: 'byron-bay', regionName: 'Byron Bay', businesses: 18 },
  { name: 'Kalgoorlie', slug: 'kalgoorlie', state: 'WA', regionSlug: 'kalgoorlie', regionName: 'Kalgoorlie', businesses: 18 },
  { name: 'Belmore', slug: 'belmore', state: 'NSW', regionSlug: 'sydney-south-west', regionName: 'Sydney South West', businesses: 18 },
  { name: 'Lilydale', slug: 'lilydale', state: 'VIC', regionSlug: 'yarra-valley', regionName: 'Yarra Valley', businesses: 18 },
  { name: 'Upper Coomera', slug: 'upper-coomera', state: 'QLD', regionSlug: 'gold-coast', regionName: 'Gold Coast', businesses: 18 },
  { name: 'Corrimal', slug: 'corrimal', state: 'NSW', regionSlug: 'wollongong', regionName: 'Wollongong', businesses: 18 },
  { name: 'Geelong West', slug: 'geelong-west', state: 'VIC', regionSlug: 'geelong', regionName: 'Geelong', businesses: 18 },
  { name: 'Coogee', slug: 'coogee', state: 'NSW', regionSlug: 'sydney-eastern-suburbs', regionName: 'Sydney Eastern Suburbs', businesses: 18 },
  { name: 'Pyrmont', slug: 'pyrmont', state: 'NSW', regionSlug: 'sydney-cbd', regionName: 'Sydney CBD', businesses: 18 },
  { name: 'Canning Vale', slug: 'canning-vale', state: 'WA', regionSlug: 'perth-south', regionName: 'Perth South', businesses: 17 },
  { name: 'Hope Island', slug: 'hope-island', state: 'QLD', regionSlug: 'gold-coast', regionName: 'Gold Coast', businesses: 17 },
  { name: 'Mudgeeraba', slug: 'mudgeeraba', state: 'QLD', regionSlug: 'gold-coast', regionName: 'Gold Coast', businesses: 17 },
  { name: 'Bondi Beach', slug: 'bondi-beach', state: 'NSW', regionSlug: 'sydney-eastern-suburbs', regionName: 'Sydney Eastern Suburbs', businesses: 17 },
  { name: 'Ringwood', slug: 'ringwood', state: 'VIC', regionSlug: 'melbourne-east', regionName: 'Melbourne East', businesses: 17 },
  { name: 'Hillarys', slug: 'hillarys', state: 'WA', regionSlug: 'perth-north', regionName: 'Perth North', businesses: 17 },
  { name: 'Gosnells', slug: 'gosnells', state: 'WA', regionSlug: 'perth-south', regionName: 'Perth South', businesses: 17 },
  { name: 'North Adelaide', slug: 'north-adelaide', state: 'SA', regionSlug: 'adelaide-cbd', regionName: 'Adelaide CBD', businesses: 17 },
  { name: 'Braddon', slug: 'braddon', state: 'ACT', regionSlug: 'canberra', regionName: 'Canberra', businesses: 17 },
  { name: 'Belconnen', slug: 'belconnen', state: 'ACT', regionSlug: 'canberra', regionName: 'Canberra', businesses: 17 },
  { name: 'Victoria Point', slug: 'victoria-point', state: 'QLD', regionSlug: 'brisbane-east', regionName: 'Brisbane East', businesses: 17 },
  { name: 'Glenroy', slug: 'glenroy', state: 'VIC', regionSlug: 'melbourne-north', regionName: 'Melbourne North', businesses: 17 },
];
